site_name: Notas UCR

theme:
  name: material

  language: es
  logo: assets/logo.svg
  favicon: assets/logo.svg
  palette:
    - scheme: default
      primary: deep orange
      accent: green

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - content.code.copy
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
      


nav:
  - Inicio: index.md
  - Cursos:
      - Introducción a la Economía para Economistas: courses/intro_econ_econ/index.md
      - Microeconomia II: courses/Microeconomia II/index.md